language: node_js
node_js:
- 8.10.0
before_script:
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: wparad@gmail.com
  api_key:
    secure: kx74f5DB2/51pLBFVA5q4OSz+ZKyvAL98tFREeiAn32UwNYgamw6KGJbzJGmRsePB3VI75IL+gbH3utt0+OvPMfoVj/LxcMTyplTVcmH0aJREg/RtUBDXxA7ji05p0AMucTIGsIahocdPIflCERq3/vu6LH145TyYfMc9tk0GGfnsN9KtJk0E3z6KjmHOl9EA5KeZ2H3pWv2dzhyaw+g2mKYzV7AIzuWWk4LosJghkgQIwhk067wt5Uqweh3EVIEGTl5Lzh48MvP6fRME15nwbGF6+SrIGm9ax0B9PyBDZ+WdURvXcPPwjpHcsbkAZ/V2tbijWqDfn7336eIRtdpGvOcxB4diTyR4Ux52FNHQ04JoheB29CeI9EyE65XNO2RK3o1g5Zj1LbSzLWZ3llJ6EfgoNgjChybT1klG6z3iLCZdBWTf+0+Lkc0gBqnQCMT8Lph8GzoI0KM73GX9cA3SsDcPK4fuBGfLKYp06VumozP1SkwNT2ZekmyxyHleGP/cpYI0EwqcwIsn3IZUxRbJjdjWSbAj6hTOKgCysY6Dkni7dTclQaHkusXneOe0cxglig5TMpJ1KhDx9h7CsukegwM4RHebtBCXQj/dWT/o9W8FsAqHPktimyDHmUAFXTyqswZFkx16TbK2tlhbh087L0n0cZM1NRld8MW0OJcIKM=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: 1fRNbPtfcTTT4Gpi/TnVXZj6hTD8E6jc5/NyZ9Bx9iMxFk+3glb2a6XpO/qUJWqAkeujsEjp0pbfsk8IQlRpo4LlA8Gw7Nh12JZBziAmks70mGMBAhDR+aDN9Hc4yGsAudtqJJoY3O0X+X7v+o+dEkryVwOArYTCLr8khgu5E6Syd7ATdVO/Yt6lftfdzxdecmjh6monyxGP070vJdNYgrbsEoaBPNpeJNyU3K5KxCoioHhRdpK7BWNSlU4vrWJSn+aZ/Xh+2AWWPxdeNZStMGhxWEMr1Ze0IUoi4LnAZrYenZKXSH4wz1zp5PzOlGp2B2EMzLmkX9I3jb3N0e+zjfG9tm1oJsCuAABft8cKjRP38YsfTu0Iw3eJ7EakP2RPPtn1/hfX5Pa1KdtyhnRlEg4ZD/j32OC4AkDaBEmyEq9whzsux7gM0KG2uJho5xVUR/rrR3uJ0bVKtLw9bPpItTi+I77PT8l2gl9fct0YGc4KCXf4bkKmla8nFeeR2RFLZ2MVZc8DEq2fmsEQon7y5mn5HH1ypZpqqyZdRxyuUjDTlXs+PC6jOOe9zUXVwbj1c18kY5dMCIctc8SoHvZlu6HQrcDzLD7O/ppnIw6KsAB29J7zW+d6wDaAedrHCE5T4fu0i+5D9APBXz4I8qCF5Yw/MihzN48nv7CwUZdF8wU=
